//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('characters')
export class charactersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  richness: string;

  @Column('bool', { nullable: true })
  lifeLike: boolean;

  @Column('text', { nullable: true })
  traditionalCostumes: string;
}
