//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('players')
export class playersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  eyePowers: number;

  @Column('integer', { nullable: true })
  firePowers: number;

  @Column('integer', { nullable: true })
  waterPowers: number;

  @Column('integer', { nullable: true })
  earthPowers: number;
}
