//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('pokemons')
export class pokemonsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('bool', { nullable: true })
  giganticPowerActivation: boolean;

  @Column('bool', { nullable: true })
  powerMaximization: boolean;

  @Column('text', { nullable: true })
  attackMechanism: string;
}
