//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('transformations')
export class transformationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  evolutionProcess: string;

  @Column('text', { nullable: true })
  targetCharacter: string;

  @Column('bool', { nullable: true })
  suitabilityToPosition: boolean;
}
