//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('upgrades')
export class upgradesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('bool', { nullable: true })
  eyesOfTheSharingan: boolean;
}
