//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    players: [
      { eyePowers: 1, firePowers: 1, waterPowers: 1, earthPowers: 1, id: 1 },
      { eyePowers: 2, firePowers: 2, waterPowers: 2, earthPowers: 2, id: 19 },
      { eyePowers: 3, firePowers: 3, waterPowers: 3, earthPowers: 3, id: 78 },
      { eyePowers: 4, firePowers: 4, waterPowers: 4, earthPowers: 4, id: 32 },
      { eyePowers: 5, firePowers: 5, waterPowers: 5, earthPowers: 5, id: 98 },
    ],
    roles: [
      { guardingKeyAreas: false, secretRoomForBossStage: false, id: 94 },
      { guardingKeyAreas: true, secretRoomForBossStage: true, id: 54 },
      { guardingKeyAreas: true, secretRoomForBossStage: true, id: 62 },
      { guardingKeyAreas: true, secretRoomForBossStage: true, id: 59 },
      { guardingKeyAreas: true, secretRoomForBossStage: true, id: 60 },
    ],
    tasks: [
      {
        awareness: true,
        enemyTransformationDetection: true,
        spotEnemies: true,
        id: 69,
      },
      {
        awareness: false,
        enemyTransformationDetection: true,
        spotEnemies: false,
        id: 61,
      },
      {
        awareness: true,
        enemyTransformationDetection: false,
        spotEnemies: false,
        id: 60,
      },
      {
        awareness: false,
        enemyTransformationDetection: false,
        spotEnemies: false,
        id: 70,
      },
      {
        awareness: false,
        enemyTransformationDetection: false,
        spotEnemies: false,
        id: 68,
      },
    ],
    transformations: [
      {
        evolutionProcess: 'evolutionProcess 1',
        targetCharacter: 'targetCharacter 1',
        suitabilityToPosition: true,
        id: 47,
      },
      {
        evolutionProcess: 'evolutionProcess 2',
        targetCharacter: 'targetCharacter 2',
        suitabilityToPosition: false,
        id: 0,
      },
      {
        evolutionProcess: 'evolutionProcess 3',
        targetCharacter: 'targetCharacter 3',
        suitabilityToPosition: false,
        id: 62,
      },
      {
        evolutionProcess: 'evolutionProcess 4',
        targetCharacter: 'targetCharacter 4',
        suitabilityToPosition: true,
        id: 89,
      },
      {
        evolutionProcess: 'evolutionProcess 5',
        targetCharacter: 'targetCharacter 5',
        suitabilityToPosition: true,
        id: 15,
      },
    ],
    pokemons: [
      {
        giganticPowerActivation: true,
        powerMaximization: true,
        attackMechanism: 'attackMechanism 1',
        id: 93,
      },
      {
        giganticPowerActivation: false,
        powerMaximization: false,
        attackMechanism: 'attackMechanism 2',
        id: 6,
      },
      {
        giganticPowerActivation: true,
        powerMaximization: false,
        attackMechanism: 'attackMechanism 3',
        id: 9,
      },
      {
        giganticPowerActivation: false,
        powerMaximization: false,
        attackMechanism: 'attackMechanism 4',
        id: 88,
      },
      {
        giganticPowerActivation: false,
        powerMaximization: true,
        attackMechanism: 'attackMechanism 5',
        id: 87,
      },
    ],
    upgrades: [
      { eyesOfTheSharingan: false, id: 95 },
      { eyesOfTheSharingan: true, id: 100 },
      { eyesOfTheSharingan: false, id: 13 },
      { eyesOfTheSharingan: true, id: 33 },
      { eyesOfTheSharingan: true, id: 30 },
    ],
    ninjutsus: [
      { level: 1, id: 46 },
      { level: 2, id: 6 },
      { level: 3, id: 39 },
      { level: 4, id: 56 },
      { level: 5, id: 97 },
    ],
    voteCall: [
      { spotImposter: false, knockOut: false, id: 18 },
      { spotImposter: false, knockOut: false, id: 6 },
      { spotImposter: true, knockOut: false, id: 80 },
      { spotImposter: true, knockOut: false, id: 7 },
      { spotImposter: true, knockOut: true, id: 73 },
    ],
    characters: [
      {
        richness: 'richness 1',
        lifeLike: false,
        traditionalCostumes: 'traditionalCostumes 1',
        id: 52,
      },
      {
        richness: 'richness 2',
        lifeLike: true,
        traditionalCostumes: 'traditionalCostumes 2',
        id: 33,
      },
      {
        richness: 'richness 3',
        lifeLike: true,
        traditionalCostumes: 'traditionalCostumes 3',
        id: 50,
      },
      {
        richness: 'richness 4',
        lifeLike: false,
        traditionalCostumes: 'traditionalCostumes 4',
        id: 5,
      },
      {
        richness: 'richness 5',
        lifeLike: false,
        traditionalCostumes: 'traditionalCostumes 5',
        id: 75,
      },
    ],
  },
};
export default data;
